#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <time.h>


void phistogram (double *minvalue, double *maxvalue, int bincount, int N,char *infile, char *outfile){
	//Create file to write from file that is reading 
    FILE *fr = fopen(infile, "r");
    FILE *fw = fopen(outfile, "wb");
    if (fr == NULL){
        exit(EXIT_FAILURE);
    }
	//str array keeps each line from a reading input file 
    char str[1024];
    double numb[1024];
    int lineNumb = 0;
    double n = 0.0;
	//str elements are converted double and keeps these values another array
    while(fgets (str, 1024, fr)){
       n = strtod(str,NULL);
       numb[lineNumb] = strtod(str,NULL);
	   lineNumb++;
    }

    int i  = 0;
    double min = numb[0];
    double max = numb[0];
    (*minvalue) = min;
    (*maxvalue) = max;

    /*
     * Find maximum and minimum in all numb[] array elements.
     */
    for(i=0; i < lineNumb; i++)
    {
        /* If current element is greater than max */
        if(numb[i] > max)
        {
            max = numb[i];
        }

        /* If current element is smaller than min */
        if(numb[i] < min)
        {
            min = numb[i];
        }
    }
    (*minvalue) = min;
    (*maxvalue) = max;

	// diff1 / diff2 gives "w" value.
    double diff1 = (max-min);
    double w = diff1/ bincount;
    char hist[256];
    int count = 0;
    int inc = 0;
    for(int i = 1; i<bincount+1; i++){
        for(int j = 0; j < lineNumb; j++){
            if(numb[j] >= (min+inc) && numb[j] < (min + inc + w)){ // to find how many numbers are in these range
                count++;
            }
        }
        inc = inc + w;						 // increments [min+w, min+2w). 
        sprintf(hist, "%d", count);				 // every count value (number of values in the range) keeps w array
        fprintf(fw, "%d:", i);        // write first Binnumber i: 
        fprintf(fw, "%s", hist);							 // write count after binumber 	
        putc('\n', fw);
        count = 0;
    }
   //close reading and writing file	   	
   fclose(fw);
   fclose(fr);

}

int main(char argc, char **argv)
{
	/*struct timeval start, end;
	start.tv_usec = 0;
  	end.tv_usec = 0;
  	gettimeofday(&start, NULL);*/

    int bincount = atoi(argv[1]);
    int InputsNumb = atoi(argv[2]);
    double minvalue,maxvalue;
    char outfile;
	// We need to create child process (number of Inputs Number)
    for(int i = 0; i < InputsNumb; i++)
    {

        pid_t childProcessId = fork();

        if(childProcessId < 0){
            printf("\nNot Created Child Process");
            exit(1);
        }
        else if(childProcessId == 0) {

            char outfile[1024];
            sprintf(outfile, "%d.txt", i+1); // create intermediate output files
            phistogram(&minvalue , &maxvalue ,bincount,InputsNumb,argv[i+3],outfile); // calling phistogram method.
	    	_exit(0);

        }
        else{
            wait(0);
        }

    }
    //sum up all data to one output file
    FILE *fr, *fw;
    char str[1024];
    fw = fopen(argv[InputsNumb + 3], "wb");
    int count = 0;
    int s[1024];
    int sum2[1024];
    int j = 0;
    int sum = 0;
    char dest[1] = { 0 }; // 4 chars + terminator */
    for (int i = 1; i <= InputsNumb; i++) {
		// read all inputs file and keeps bin1 bin2.. so on into an array separetely.
		// After "binnumber:" number value is converted integer and added to sum    
        sprintf(str, "%d.txt", i);  //create main output
        fr = fopen(str, "rb");
		
		if (fr == NULL){
			exit(EXIT_FAILURE);
		}

        while (fgets (str, 1024, fr)) {

            int len = strlen(str);
            int a = 2;
            strncpy(dest, str+(a*1), 4);
            s[count] = atoi(dest);
            count++;
        }
    }
    for(int k = 1; k < bincount + 1; k++){
        while(j < count){
            sum = sum + s[j];
            j = j + bincount;
        } 
		// Write all results for bin1: bin2: ... so on into the output file that is generated by main process.
        fprintf(fw, "%d:", k);
        fprintf(fw, "%d", sum);
        putc('\n', fw);
        sum = 0;
        j = k;
    }

    fclose(fw);
    fclose(fr);
	/*
   	gettimeofday(&end, NULL);
	long seconds = end.tv_sec - start.tv_sec;
	long micro_seconds = end.tv_usec - start.tv_usec;
	long total_micro_seconds = (seconds * 1000000) + abs(micro_seconds);
	printf("The program took: %ld milliseconds.\n", total_micro_seconds);*/

    return 0;
}




